# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: adam price
email: komidore64@gmail.com

#write html inside the double quotes to display in jumbotron
description: "<h1>maprys.net</h1><h3>ramblings, tutorials, and tech things</h3>"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://komidore64.github.io" # the base hostname & protocol for your site
twitter_username: komidore64
github_username:  komidore64

# Build settings
markdown: kramdown
